### ISSUE TITLE
Space in email template

### ISSUE THREAD

**Issue by alanef** [alanef/clean-and-simple-contact-form-by-meg-nicholas#4]
https://wordpress.org/support/topic/line-breaks-in-email-template/

**Comment by nepa** [comment]
@alanef : This one is tricks. The code is correct. There is no space, because it is missing in the German translation of "Email: ".

**Clean solution:** Move colons from translation to code. However, we need to update all translations of the labels then.

**Pragmatic solution:** Add missing space to German translation of "Email: ".

I would prefer the clean solution, because IMHO the colons and spaces do not belong in the translation.
